/*******************************************************************************
 * Exercises 7.7 from Programming in C
 * File:    program7.7.c
 * 
 * Victor Barriga 
 * victorbarriga@live.com
 * 
 * 7. Prime numbers can also be generated by an algorithm known as the Sieve of 
 * Erastosthenes.The algorithm for this procedure is presented here.Write a 
 * program that implements this algorithm. Have the program find all prime 
 * numbers up to n = 150.What can you say about this algorithm as compared to 
 * the ones used in the text for calculating prime numbers?
		Sieve of Erastosthenes Algorithm
		To Display All Prime Numbers Between 1 and n
		Step 1: Define an array of integers P. Set all elements P i to 0, 
				2 <= i <= n.
		Step 2: Set i to 2.
		Step 3: If i > n, the algorithm terminates.
		Step 4: If Pi is 0, then i is prime.
		Step 5: For all positive integer values of j, such that i x j ≤ n, 
				set Pixj to 1.
		Step 6: Add 1 to i and go to step 3.
*******************************************************************************/

#include <stdio.h>

int main (void)
{
	int primes[151], i, j;
	int n = 150;
	
	// set all elements in array to 0.
	for ( i = 2; i <= n; ++i )
		primes[i] = 0;
	
	i = 2;
	while ( i <= n )
	{
		if ( primes[i] == 0 )
			printf ("%i ", i);
			
			j = 1;			
			// check current i and j in primes[] input 1 if multiple appllies.
			while ( i * j <= n )
			{
				primes[ i * j ] = 1;
				++j;
			}
			
			++i;
	}
	return 0;
}
