/*******************************************************************************
 * Exercises 5.3 from Programming in C
 * File:    exercise5.3.c
 * 
 * Victor Barriga 
 * victorbarriga@live.com
 * 
 * 3. A triangular number can also be generated by the formula triangularNumber 
 * = n (n + 1) / 2 for any integer value of n. 
 *
 * For example, the 10th triangular number, 55, can be generated by substituting
 * 10 as the value for n in the preceding formula. 
 *
 * Write a program that generates a table of triangular numbers using the 
 * preceding formula. Have the program generate every fifth triangular number 
 * between 5 and 50 (that is, 5, 10, 15, ..., 50).
 *
*******************************************************************************/

#include <stdio.h>

int main (void)
{
	// initialize variables
	int number, triangular_number, counter;
	do
	{
	// receive input from user, up to what number should the table be generated
	printf ("Using ONLY multiples of 5, "); 
	printf ("what is the last number the table should generate?\n ");
	scanf ("%i", &number);
	}
	while (number % 5 != 0 );
	
	// print to console title, header, tables to console
	printf ("\n*******************************\n");
	printf ("* TABLE OF TRIANGULAR NUMBERS *\n");
	printf ("*******************************\n\n");
	printf (" n     Triangular Number\n");
	printf ("---   -------------------\n");
	
	// repeat n times using counter, calculate triangugar num & print to console
	for ( counter = 5; counter <= number; counter += 5)
	{
		triangular_number = counter * (counter + 1) / 2;
		printf (" %2i		%i\n", counter, triangular_number);
	}
	printf ("-------------------------\n");
	return 0;
}
